### ISSUE TITLE
Odd top-200 network results

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#17]
Having trouble making sense of this... 

Steps to reproduce:
1. load E-MTAB-7365
2. DE on K=5
3. Check heatmap (screenshot)
4. Note Cluster 3 has STRONG positive set, e.g., 27.598. Also note DE table (screenshot)
5. Make networks of top 200
6. Note cluster 3 only includes positive genes as high as 8.55 (screenshot)

Why are the top positive genes missing from network?  I pulled them from the exported csv and did a separate STRING query. The Ensembl IDs for the 31 positive genes with values greater then 8.55 returned a network with 20 nodes. They are unconnected, but should be in the top-200 network, right? 

![Screen Shot 2019-09-06 at 1 50 27 PM](https://user-images.githubusercontent.com/1418193/64460298-e5cfd280-d0ae-11e9-85d2-21c168fdc09f.png)

![Screen Shot 2019-09-06 at 1 52 36 PM](https://user-images.githubusercontent.com/1418193/64460321-f2ecc180-d0ae-11e9-8119-234546fadf32.png)

![Screen Shot 2019-09-06 at 2 03 13 PM](https://user-images.githubusercontent.com/1418193/64460389-20d20600-d0af-11e9-94fe-ce2eb31877f8.png)

**Comment by scootermorris** [comment]
Actually, that's correct.  We choose the top genes based on the p-value, and the p-value for those genes is 1x10-3.  Should we use the log2FC instead to avoid surprises?

**Comment by scootermorris** [comment]
OK, thinking about this, I agree that it's confusing.  How about we change the definition of "top genes" to say the genes with the top differential expression that pass a cutoff of 0.05 FDR (not p-value).  Does that make sense?

**Comment by AlexanderPico** [comment]
Yes, I agree.

**Comment by scootermorris** [comment]
Slight fly in the ointment.  If we're looking for the top 50 genes in each category, are we looking for the top expression based on absolute value (assuming positiveOnly isn't set)?  Or are we looking for the top 25 overexpressed and the top 25 underexpressed?  The latter approach is going to give results that will align with the heatmaps, but also a pretty biased look at the network.  The former approach may still result in a difference between the heatmap and the network.

**Comment by AlexanderPico** [comment]
I think we are looking for the top expression based on absolute value for networks. Even though it won't match the heatmap selection perfectly, the reasonable expectation for overap will be met, i.e., for _at least_ the most positive or negative values (if not both) to be included.

**Comment by AlexanderPico** [comment]
Relating back  to "marker" gene sets, I might even argue that the heatmap should be based on absolute values as well. The top/bottom 10 makes for a nicely balanced image that is consistent across categories (and across experiments), but I might actually want to the see a heatmap of my top 20 marker genes overall...

**Comment by scootermorris** [comment]
Ugh.  This just keeps getting better and better.  So, I changed everything over to sort by the absolute expression values, and.....those genes still didn't show up!  Turns out that there are two issues with those genes:

1. They don't meet the FDR threshold of 0.05, so they are dubious, but more importantly,
1. They are pseudo-genes and don't have protein entries, so they won't show up in STRING.

I propose the following changes:

1. Change our "either/or" cutoffs or top gene in the Differential Expression Tab to "cutoffs + max genes".  This will avoid some confusion as long as we also....
1. Use the current settings for cutoffs to create the heatmaps.  We already respect the "positive Only" checkbox, so I'm proposing that we also respect all of the other values in the form.  This will allow our heatmaps to be more reflective.  

Nothing much we can do in this round about pseudogenes.  I think that eventually, we may want to add a "filter genes" option that will drop pseudogenes, mitochondrial genes, etc.
