### ISSUE TITLE
Search is buggy in SCEA browser

### ISSUE THREAD

**Issue by khanspers** [RBVI/scNetViz#33]
Search seems buggy in several ways:
- Searching for Accession number doesn't work. I tried searching for the exact accession number, as well as part of it.
- Searching for keyword (for example appearing in Experiment description) doesn't seem to find the correct experiment, and sometimes find seemingly incorrect ones. Try "lung" or "colon" for example.

**Comment by scootermorris** [comment]
OK, fixed as follows:
1) I changed it so that the Accession is an exact match, so if you search for E-CURD-2 you won't get E-CURD-21.
2) Fixed bug where entry contents were being converted to lower case, but search string wasn't
3) Fixed bug where the table indices weren't being converted by to the view.
